#!/usr/bin/env bun
import { join } from "node:path";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { HOME } from "../src/lib/vault.ts";
import type { AssetRecord, Manifest } from "../src/lib/types.ts";

/**
 * Fold the Pro vault into the same library the free components live in.
 *
 * Pro assets appear as ordinary sidebar entries carrying a PRO badge rather than
 * living in a separate section, so one search and one sidebar cover everything.
 * Generated from the manifest and idempotent — re-run after any vault change.
 */

const VENDOR = join(HOME, "site");
const START = "// >>> foxbits:pro (generated by scripts/add-pro.ts — do not edit)";
const END = "// <<< foxbits:pro";

const title = (slug: string) =>
  slug.split("-").map((w) => (/^\d+$/.test(w) ? w : w.charAt(0).toUpperCase() + w.slice(1))).join(" ");

/** Sidebar links are built as slug(label), so the label must round-trip. */
const slugOf = (label: string) => label.toLowerCase().replace(/\s+/g, "-");

/**
 * Official component groups from upstream's own pro-manifest.json (vendored to
 * gallery/public/ so the site's search hook can also fetch it offline). Each
 * component carries a `group`; the map below is only the fallback for anything
 * the manifest doesn't cover.
 */
const GROUP_FALLBACK: [string, string[]][] = [
  ["Text", ["text", "ascii", "marquee"]],
  ["Cursor Effects", ["cursor"]],
  ["Backgrounds", ["background", "ambient", "particles", "dots"]],
  ["3D & Shaders", ["shader", "3d", "webgl", "canvas"]],
];

async function loadProGroups(): Promise<Map<string, string>> {
  const map = new Map<string, string>();
  try {
    const m = JSON.parse(await readFile(join(HOME, "gallery/public/pro-manifest.json"), "utf8"));
    for (const a of m.assets ?? []) {
      if (a?.slug && a?.group && typeof a.href === "string" && a.href.includes("/components/")) {
        map.set(a.slug, a.group);
      }
    }
  } catch { /* fall back to tags for everything */ }
  return map;
}

function groupFallback(tags: string[]): string {
  for (const t of tags) for (const [name, members] of GROUP_FALLBACK) if (members.includes(t)) return name;
  return "UI & Cards";
}

/**
 * (Blocks are not published — see below — but the bucket table is kept for the
 * day they come back.)
 */
const BUCKETS: [string, string[]][] = [
  ["Landing", ["hero", "landing", "cta", "social-proof", "features", "how-it-works", "comparison", "showcase", "waitlist", "download", "faq", "about", "testimonials", "logos"]],
  ["App UI", ["shell", "dashboard", "kanban", "wizard", "onboarding", "overlay", "notifications", "profile", "chat", "comments", "feedback", "filter", "list", "card", "table", "settings", "modal", "editor", "calendar", "search", "upload", "empty"]],
  ["Data", ["analytics", "charts", "data", "metrics", "stats", "monitoring", "reports"]],
  ["Auth", ["auth", "login", "signup", "billing", "paywall", "pricing", "plans", "checkout"]],
  ["Navigation", ["navigation", "navbar", "header", "footer", "menu", "sidebar", "breadcrumb", "tabs"]],
  ["Forms", ["form", "forms", "contact", "scheduling", "integrations", "newsletter", "survey"]],
  ["AI", ["ai", "agent", "prompt", "assistant"]],
  ["Commerce", ["ecommerce", "blog", "product", "cart", "gallery", "media", "docs", "changelog", "404", "error"]],
];

function bucketFor(tags: string[]): string {
  for (const t of tags) {
    for (const [name, members] of BUCKETS) if (members.includes(t)) return name;
  }
  return "Misc";
}

/**
 * Pro components ship no demos, so nothing supplies their props. Several bail
 * out early on missing content (StaggeredText does `if (!text) return null`),
 * which renders an empty stage. Read the declared props and fill in the content
 * ones so a preview shows something representative.
 */
async function inferDemoProps(variant: { files: { path: string }[] } | undefined, title: string) {
  const file = variant?.files.find((f) => /\.(tsx|jsx)$/.test(f.path));
  if (!file) return {};
  let src = "";
  try { src = await readFile(join(HOME, file.path), "utf8"); } catch { return {}; }

  const props: Record<string, unknown> = {};
  const declares = (name: string) =>
    new RegExp(`(^|[\\s{,])${name}\\s*[?]?\\s*:`, "m").test(src) ||
    new RegExp(`(^|[\\s{,])${name}\\s*[=,}]`, "m").test(src);

  for (const p of ["text", "label", "title", "heading", "caption"]) {
    if (declares(p)) { props[p] = title; break; }
  }
  if (/\bchildren\b/.test(src) && !("text" in props)) props.children = title;
  return props;
}

type ControlSchema = {
  stage?: string;
  demoProps?: Record<string, unknown>;
  controls?: unknown[];
  notes?: string;
};

/**
 * Agent-extracted Customize schemas (scripts/data/pro-schemas.json): per-prop
 * controls with the component's real defaults, demo props for required props,
 * and the stage type (fill/center/cursor/scroll). Regenerated by the
 * pro-customizer-schemas workflow; inferDemoProps remains the fallback for any
 * component the file doesn't cover.
 */
async function loadSchemas(): Promise<Record<string, ControlSchema>> {
  try {
    return JSON.parse(await readFile(join(HOME, "scripts/data/pro-schemas.json"), "utf8"));
  } catch {
    return {};
  }
}

type RenameRow = { slug: string; source: string; oldTitle: string; newTitle: string; newSlug: string };

/** The old ↔ new naming sheet (scripts/data/renames.json) — see CLAUDE.md. */
async function loadRenames(): Promise<Map<string, RenameRow>> {
  try {
    const rows: RenameRow[] = JSON.parse(await readFile(join(HOME, "scripts/data/renames.json"), "utf8"));
    // Post-stockroom-rename: manifest slugs ARE the new slugs; key by newSlug.
    return new Map(rows.filter((r) => r.source === "rb-starter").map((r) => [r.newSlug, r]));
  } catch {
    return new Map();
  }
}

async function main() {
  const manifest: Manifest = JSON.parse(await readFile(join(HOME, "vault/manifest.json"), "utf8"));
  const schemas = await loadSchemas();
  const renames = await loadRenames();
  // BOTH identities of every free component: componentMap still keys the old
  // slugs (compat routes) and apply-renames adds the new ones, so a Pro alias
  // colliding with either would shadow a live free page.
  const free = new Set(
    manifest.assets.filter((a) => a.source === "rb-free").flatMap((a) => [a.slug, a.upstreamSlug].filter(Boolean)),
  );
  // Components only — the user wants a component library, not pre-built
  // sections. Blocks and agent-kit stay mirrored in the vault but are not
  // published to the site.
  // Hidden by user decision — stays mirrored in the vault, not shown on the site.
  const HIDDEN_SLUGS = new Set(["blur-highlight", "marker-reveal"]); // old + stockroom-renamed slug
  const pro = manifest.assets.filter(
    (a) => a.source !== "rb-free" && a.kind === "component" && !HIDDEN_SLUGS.has(a.slug),
  );

  // componentMap is keyed by slug alone, so a Pro slug that matches a free one
  // would silently shadow it. Only the colliding few get disambiguated, so the
  // other ~689 keep clean labels.
  const collisions: string[] = [];
  const labelFor = (a: AssetRecord) => {
    const base = title(a.slug);
    if (free.has(a.slug)) {
      collisions.push(a.slug);
      return `${base} Pro`;
    }
    return base;
  };

  type Entry = { slug: string; label: string; rec: AssetRecord; aliases: string[] };
  const entries: Entry[] = pro.map((rec) => {
    const rn = renames.get(rec.slug);
    const label = rn?.newTitle ?? labelFor(rec);
    const slug = rec.slug; // manifest already carries the new slug
    // Old published slugs keep resolving (old links, muscle memory) — EXCEPT
    // when the old Pro slug is also a free component's slug (the 4 upstream
    // twins): that key belongs to the free page, and a PRO_MAP entry for it
    // would shadow the free demo loader with ProDemo ("Unknown Pro asset").
    // Twins stay reachable via their `-pro` alias.
    const aliases = rn ? [rn.slug, `${rn.slug}-pro`].filter((a) => a !== slug && !free.has(a)) : [];
    return { slug, label, rec, aliases };
  });

  // Group: components together, blocks by their primary tag, docs together.
  const groups = new Map<string, Entry[]>();
  const push = (g: string, e: Entry) => {
    if (!groups.has(g)) groups.set(g, []);
    groups.get(g)!.push(e);
  };

  const proGroups = await loadProGroups();
  for (const e of entries) {
    // Same sectioning as pro.reactbits.dev, from their own manifest: Text,
    // Backgrounds, 3D & Shaders, Cursor Effects, UI & Cards. "Deep " prefix (the PUDDL3 tier name)
    // keeps the headings distinct from the free "Backgrounds" category.
    const g = proGroups.get(e.rec.slug) ?? groupFallback(e.rec.tags);
    push(`Deep ${g}`, e);
  }

  const GROUP_ORDER = ["Deep Text", "Deep Backgrounds", "Deep 3D & Shaders", "Deep Cursor Effects", "Deep UI & Cards"];
  const ordered = [...groups.entries()].sort(
    ([a], [b]) => (GROUP_ORDER.indexOf(a) + 99 * +(GROUP_ORDER.indexOf(a) < 0)) - (GROUP_ORDER.indexOf(b) + 99 * +(GROUP_ORDER.indexOf(b) < 0)),
  );

  const toCat = ([name, list]: [string, Entry[]]) => ({
    name,
    subcategories: [...list].sort((p, q) => p.label.localeCompare(q.label)).map((e) => e.label),
  });
  // The library keeps only components; blocks and the agent kit form a separate
  // "Sections" zone with its own sidebar (the user wants a component library
  // first, pre-built sections as their own area).
  const categories = ordered.map(toCat);
  const sectionCategories: ReturnType<typeof toCat>[] = [];

  // Per-slug metadata ProDemo reads at render time.
  const index: Record<string, unknown> = {};
  for (const e of entries) {
    const v = e.rec.variants.find((x) => x.id === e.rec.defaultVariant) ?? e.rec.variants[0];
    const schema = schemas[e.slug] ?? schemas[e.rec.slug] ?? {};
    const displayTitle = (e.rec.title ?? e.rec.slug).replace(/\s*\((CSS|Tailwind|TW)\)\s*$/i, "");
    index[e.slug] = {
      displayTitle,
      demoProps: schema.demoProps ?? (await inferDemoProps(v, e.rec.title)),
      controls: schema.controls ?? [],
      stage: schema.stage,
      // Full-bleed components (WebGL, shaders, backgrounds) size themselves off
      // the parent; flex-centering shrink-wraps them into a narrow strip.
      fill: e.rec.requires.webgl || e.rec.tags.some((t) => ["background", "shader", "webgl", "cursor"].includes(t)),
      id: e.rec.id,
      title: displayTitle,
      description: e.rec.description,
      kind: e.rec.kind,
      tags: e.rec.tags,
      file: v?.files.find((f) => /\.(tsx|jsx|md)$/.test(f.path))?.path ?? v?.files[0]?.path ?? "",
      exportName: e.rec.exports[0]?.name ?? "",
      dependencies: e.rec.dependencies.map((d) => d.name),
    };
  }

  for (const e of entries) {
    for (const a of e.aliases) {
      if (!index[a]) index[a] = index[e.slug];
    }
  }

  await mkdir(join(VENDOR, "constants"), { recursive: true });
  await writeFile(join(VENDOR, "constants/ProCatalog.js"),
    `// Generated by scripts/add-pro.ts from vault/manifest.json — do not edit by hand.
// Re-run after any vault change.

export const PRO_CATEGORIES = ${JSON.stringify(categories, null, 2)};

// Pre-built sections (blocks) + Agent Kit — a separate zone from the library.
export const SECTION_CATEGORIES = ${JSON.stringify(sectionCategories, null, 2)};

export const PRO_INDEX = ${JSON.stringify(index, null, 2)};

// Every Pro slug renders through the same generic demo, which resolves the
// source from the vault using PRO_INDEX.
export const PRO_MAP = Object.fromEntries(
  Object.keys(PRO_INDEX).map(slug => [slug, () => import('../demo/Pro/ProDemo.jsx')])
);

export const PRO_LABELS = new Set(PRO_CATEGORIES.flatMap(c => c.subcategories));
`, "utf8");

  await patchCategories();
  await patchComponents();
  await patchZones();
  await patchCli();
  await patchMarkdownItem();

  const total = entries.length;
  console.log(`✓ ${total} Pro assets — library: ${categories.map((c) => `${c.name} (${c.subcategories.length})`).join(", ")}`);
  console.log(`  sections zone: ${sectionCategories.map((c) => `${c.name} (${c.subcategories.length})`).join(", ")}`);
  if (collisions.length) console.log(`  disambiguated (slug clashed with a free component): ${collisions.join(", ")}`);
}

/** Append the generated categories to CATEGORIES, between markers so re-runs replace. */
async function patchCategories() {
  const p = join(VENDOR, "constants/Categories.js");
  let s = await readFile(p, "utf8");
  s = stripBlock(s);
  if (!s.includes("PRO_CATEGORIES")) {
    s = `import { PRO_CATEGORIES } from './ProCatalog';\n` + s;
  }
  s += `\n${START}\nCATEGORIES.push(...PRO_CATEGORIES);\n${END}\n`;
  await writeFile(p, s, "utf8");
}

/** Merge PRO_MAP into componentMap. */
async function patchComponents() {
  const p = join(VENDOR, "constants/Components.js");
  let s = await readFile(p, "utf8");
  s = stripBlock(s);
  if (!s.includes("PRO_MAP")) {
    s = `import { PRO_MAP } from './ProCatalog';\n` + s;
    s = s.replace(
      /export const componentMap = \{([\s\S]*?)\};/,
      // The last spread has no trailing comma upstream, so one must be added or
      // the appended entry is a syntax error.
      (_m, body) => `export const componentMap = {${body.replace(/\s*$/, "")},\n  ...PRO_MAP\n};`,
    );
  }
  await writeFile(p, s, "utf8");
}

/**
 * Make the sidebar zone-aware and repoint the top nav.
 *
 * Library routes show the ordinary categories; any route whose first segment is
 * a section-category slug shows SECTION_CATEGORIES instead. The old sidebar
 * "Pro" quick-links (PRO_SECTIONS) pointed at upstream's remote-manifest pages,
 * so they are disabled outright. All edits are guarded so re-runs are no-ops.
 */
async function patchZones() {
  const sidebar = join(VENDOR, "components/navs/Sidebar.jsx");
  let s = await readFile(sidebar, "utf8");
  const before = s;

  if (!s.includes("SECTION_CATEGORIES")) {
    s = s.replace(
      "import { PRO_SECTIONS } from '../../constants/Pro';",
      "import { PRO_SECTIONS } from '../../constants/Pro';\nimport { SECTION_CATEGORIES } from '../../constants/ProCatalog';",
    );

    // The active-item finder must search both zones or the highlight bar
    // disappears on section routes.
    s = s.replace(
      "for (const category of CATEGORIES) {",
      "for (const category of [...CATEGORIES, ...SECTION_CATEGORIES]) {",
    );

    // Choose the visible list from the current route.
    s = s.replace(
      "  return (\n    <>\n      <MainDrawer",
      "  // Zone switch: section routes get the sections sidebar, everything else\n" +
        "  // gets the component library.\n" +
        "  const ZONE_CATEGORIES = SECTION_CATEGORIES.some(c => location.pathname.startsWith(`/${slug(c.name)}/`))\n" +
        "    ? SECTION_CATEGORIES\n" +
        "    : CATEGORIES;\n\n" +
        "  return (\n    <>\n      <MainDrawer",
    );
    s = s.replace("categories={CATEGORIES}", "categories={ZONE_CATEGORIES}");
    s = s.replace("{CATEGORIES.map((cat, i) => (", "{ZONE_CATEGORIES.map((cat, i) => (");

    // Old Pro quick-links: desktop block and mobile drawer component.
    s = s.replace(
      /\{\/\* Pro Section - after Get Started \*\/\}\s*\n(\s*)\{i === 0 && \(/,
      "{/* Upstream Pro quick-links removed — sections have their own zone */}\n$1{false && (",
    );
    s = s.replace("<ProLinks onClose={onClose} />", "{null}");
  }

  if (s !== before) {
    await writeFile(sidebar, s, "utf8");
    console.log("  sidebar: zone switching wired, old Pro links disabled");
  }

  // Top nav: Pro → Sections.
  const navbar = join(VENDOR, "components/landingnew/Navbar/Navbar.jsx");
  let n = await readFile(navbar, "utf8");
  const nb = n;
  n = n.replace(
    "{ label: 'Pro', to: '/pro', match: '/pro' },",
    "{ label: 'Sections', to: '/landing/about-1', match: '/landing' },",
  );
  if (n !== nb) {
    await writeFile(navbar, n, "utf8");
    console.log("  navbar: Pro → Sections");
  }
}

/**
 * The Copy-install-command toolbar builds free-registry commands
 * (@react-bits/Name-TS-TW). Pro components live in a different registry with
 * different naming (@reactbits-starter/<slug>-tw), so route categories starting
 * with "pro-" get the real Pro command instead.
 */
async function patchCli() {
  const p = join(VENDOR, "utils/cli.js");
  let s = await readFile(p, "utf8");
  if (s.includes("foxbits:pro-cli") || s.includes("foxbits:own-ecosystem")) return;
  s = s.replace(
    "export const generateCliCommands = (language, style, category, subcategory, dependencies = '') => {\n  if (!category || !subcategory) return null;",
    `export const generateCliCommands = (language, style, category, subcategory, dependencies = '') => {
  if (!category || !subcategory) return null;

  // foxbits:pro-cli — Pro components install from the reactbits-starter
  // registry with -tw/-css suffixes; language preset does not apply (TS only).
  if (category.startsWith('pro-') || category.startsWith('deep-')) {
    const proSlug = subcategory.replace(/-pro$/, '');
    const suffix = (style || 'TAILWIND').toUpperCase().startsWith('C') ? 'css' : 'tw';
    const target = \`@reactbits-starter/\${proSlug}-\${suffix}\`;
    const prefixes = { pnpm: 'pnpm dlx', npx: 'npx', yarn: 'yarn', bun: 'bun x --bun' };
    const cmds = Object.fromEntries(
      Object.entries(prefixes).map(([mgr, prefix]) => [mgr, \`\${prefix} shadcn@latest add \${target}\`])
    );
    return { shadcn: cmds, jsrepo: cmds };
  }`,
  );
  await writeFile(p, s, "utf8");
  console.log("  cli commands: pro categories → @reactbits-starter registry");
}

/**
 * "Copy as markdown" menu item, matching the Pro site's Copy-for-AI menu.
 * ProDemo passes markdownDoc on its CodeExample; TabsLayout forwards it through
 * aiExport; the hook renders the item only when the doc is present, so free
 * pages (which don't pass one) are unchanged.
 */
async function patchMarkdownItem() {
  const tl = join(VENDOR, "components/common/TabsLayout.jsx");
  let t = await readFile(tl, "utf8");
  if (!t.includes("foxbits:markdown-item")) {
    t = t.replace(
      "      dependencies: codeObject.dependencies || ''\n    };",
      "      dependencies: codeObject.dependencies || '',\n      markdownDoc: codeExampleProps.markdownDoc // foxbits:markdown-item\n    };",
    );
    await writeFile(tl, t, "utf8");
  }

  const hook = join(VENDOR, "hooks/useAIExportActions.js");
  let h = await readFile(hook, "utf8");
  if (!h.includes("foxbits:markdown-item")) {
    h = h.replace(
      "export function useAIExportActions({\n  componentName,",
      "export function useAIExportActions({\n  markdownDoc, // foxbits:markdown-item\n  componentName,",
    );
    h = h.replace(
      `      {
        key: 'install',
        label: 'Copy install command',
        icon: Terminal,
        run: () => run('install', installCommand, 'Install command copied')
      }
    ];`,
      `      {
        key: 'install',
        label: 'Copy install command',
        icon: Terminal,
        run: () => run('install', installCommand, 'Install command copied')
      },
      ...(markdownDoc
        ? [{
            key: 'markdown',
            label: 'Copy as markdown',
            icon: FileText,
            run: () => run('markdown', markdownDoc, 'Markdown copied')
          }]
        : [])
    ];`,
    );
    h = h.replace(
      "  }, [componentName, componentCss, componentSource, fullPrompt, configuredUsage, installCommand, run]);",
      "  }, [componentName, componentCss, componentSource, fullPrompt, configuredUsage, installCommand, markdownDoc, run]);",
    );
    await writeFile(hook, h, "utf8");
  }
  console.log("  Copy-as-markdown menu item wired");
}

function stripBlock(s: string) {
  const i = s.indexOf(START);
  if (i === -1) return s;
  const j = s.indexOf(END, i);
  return s.slice(0, i) + s.slice(j === -1 ? i : j + END.length);
}

main();
