#!/usr/bin/env bun
import { join } from "node:path";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { HOME } from "../src/lib/vault.ts";
import type { Manifest } from "../src/lib/types.ts";

/**
 * Publish the GetLayers templates (vault/getlayers) as the site's Templates
 * zone. Run AFTER add-pro.ts — it patches the SECTION_CATEGORIES line that
 * add-pro regenerates. Idempotent.
 *
 * Sidebar shows TEMPLATE NAMES; the content inside speaks PUDDL3 (user rule).
 */

const VENDOR = join(HOME, "vendor/reactbits");
const START = "// >>> foxbits:templates (generated by scripts/add-templates.ts — do not edit)";
const END = "// <<< foxbits:templates";

function stripBlock(s: string) {
  const i = s.indexOf(START);
  if (i === -1) return s;
  const j = s.indexOf(END, i);
  return s.slice(0, i) + s.slice(j === -1 ? i : j + END.length + 1);
}

async function main() {
  const manifest: Manifest = JSON.parse(await readFile(join(HOME, "vault/manifest.json"), "utf8"));
  const gl = manifest.assets.filter((a) => a.source === "getlayers");
  const order = (a: any) => (a.kind === "scene" ? 1 : 0);
  gl.sort((a, b) => order(a) - order(b) || a.title.localeCompare(b.title));

  const index: Record<string, unknown> = {};
  for (const a of gl) {
    index[a.slug] = {
      title: a.title,
      kind: a.kind,
      note: a.description,
      brand: (a as any).brand?.contentBrand ?? "PUDDL3",
      tagline: (a as any).brand?.tagline ?? "",
      stage: a.kind === "scene" ? `/scene/${a.slug}/index.html` : `/template.html?t=${a.slug}`,
    };
  }

  // ── TemplatesCatalog.js ──────────────────────────────────────────────────
  await writeFile(join(VENDOR, "constants/TemplatesCatalog.js"),
    `// Generated by scripts/add-templates.ts from vault/manifest.json — do not edit.
export const TEMPLATE_CATEGORIES = [
  { name: 'Templates', subcategories: ${JSON.stringify(gl.map((a) => a.title))} },
];
export const TEMPLATE_INDEX = ${JSON.stringify(index, null, 2)};
`, "utf8");

  // ── componentMap entries ─────────────────────────────────────────────────
  const compPath = join(VENDOR, "constants/Components.js");
  let comp = stripBlock(await readFile(compPath, "utf8"));
  const lines = gl.map((a) => `componentMap['${a.slug}'] = () => import('../demo/Templates/TemplateDemo.jsx');`);
  comp += `\n${START}\n${lines.join("\n")}\n${END}\n`;
  await writeFile(compPath, comp, "utf8");

  // ── Templates rides the ONE sidebar as a normal (collapsible) category ───
  const catPath = join(VENDOR, "constants/Categories.js");
  let cat = stripBlock(await readFile(catPath, "utf8"));
  if (!cat.includes("TEMPLATE_CATEGORIES")) {
    cat = `import { TEMPLATE_CATEGORIES } from './TemplatesCatalog';\n` + cat;
  }
  cat += `\n${START}\nCATEGORIES.push(...TEMPLATE_CATEGORIES);\n${END}\n`;
  await writeFile(catPath, cat, "utf8");

  // ── per-template tailwind wrappers for the stage ─────────────────────────
  const cssDir = join(HOME, "gallery/src/template-css");
  await mkdir(cssDir, { recursive: true });
  let wrappers = 0;
  for (const a of gl) {
    if (a.kind !== "template") continue;
    await writeFile(join(cssDir, `${a.slug}.css`),
      `@import "../../../vault/getlayers/templates/${a.slug}/files/src/app/globals.css";
@source "../../../vault/getlayers/templates/${a.slug}/files/src";
`, "utf8");
    wrappers++;
  }

  // ── the demo page ────────────────────────────────────────────────────────
  await mkdir(join(VENDOR, "demo/Templates"), { recursive: true });
  await writeFile(join(VENDOR, "demo/Templates/TemplateDemo.jsx"),
    `import { useParams } from 'react-router-dom';
import { TEMPLATE_INDEX } from '../../constants/TemplatesCatalog';

// Full-page live preview of a GetLayers template (PUDDL3-branded), straight
// from the vault via /template.html (isolated iframe) or /scene/ (vanilla).
const TemplateDemo = () => {
  const { subcategory } = useParams();
  const meta = TEMPLATE_INDEX[subcategory];
  if (!meta) return <div style={{ padding: 24, color: '#f87171' }}>Unknown template: {subcategory}</div>;
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12, height: 'calc(100vh - 140px)' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 12, flexWrap: 'wrap' }}>
        <h2 style={{ margin: 0, fontSize: 24, fontWeight: 700 }}>{meta.title}</h2>
        <span style={{ opacity: 0.55, fontSize: 13 }}>
          {meta.brand}{meta.tagline ? \` — \${meta.tagline}\` : ''}
        </span>
        <span style={{ flex: 1 }} />
        <a href={meta.stage} target="_blank" rel="noreferrer"
           style={{ fontSize: 13, color: '#a78bfa', textDecoration: 'none' }}>
          open full ↗
        </a>
      </div>
      <iframe
        src={meta.stage}
        title={meta.title}
        style={{ flex: 1, width: '100%', border: '1px solid rgba(255,255,255,.08)', borderRadius: 14, background: '#000' }}
      />
    </div>
  );
};

export default TemplateDemo;
`, "utf8");

  console.log(`✓ Templates zone: ${gl.length} entries (${wrappers} css wrappers) — first route /templates/${gl[0]?.slug}`);
}

main();
