#!/usr/bin/env bun
import { join } from "node:path";
import { readFile, writeFile } from "node:fs/promises";
import { HOME } from "../src/lib/vault.ts";

/**
 * Apply the component renames (scripts/data/renames.json) to the FREE side of
 * the site: sidebar labels, NEW badges, route slugs, and the metadata lookup.
 *
 * Deterministic and idempotent, like rebrand.ts — re-vendoring upstream is
 * copy-the-tree, re-run. The Pro side is applied by add-pro.ts (which reads
 * the same sheet), and the vault always keeps upstream names internally.
 *
 * Bridge note: site route slugs come from slug(sidebar label) and do not always
 * match manifest slugs (site "ascii-text" vs manifest "asciitext"), so all
 * matching here uses a dash/space-insensitive normalized key.
 */

const VENDOR = join(HOME, "vendor/reactbits");
const START = "// >>> foxbits:renames (generated by scripts/apply-renames.ts — do not edit)";
const END = "// <<< foxbits:renames";

type Rename = { slug: string; source: string; oldTitle: string; newTitle: string; newSlug: string };

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
const slugOf = (label: string) => label.toLowerCase().replace(/\s+/g, "-");

function stripBlock(s: string) {
  const i = s.indexOf(START);
  if (i === -1) return s;
  const j = s.indexOf(END, i);
  return s.slice(0, i) + s.slice(j === -1 ? i : j + END.length + 1);
}

async function main() {
  const renames: Rename[] = JSON.parse(await readFile(join(HOME, "scripts/data/renames.json"), "utf8"));
  const free = renames.filter((r) => r.source === "rb-free");
  // Normalized lookup by both manifest slug and old title.
  const byNorm = new Map<string, Rename>();
  for (const r of free) {
    byNorm.set(norm(r.slug), r);
    byNorm.set(norm(r.oldTitle), r);
  }

  // ── Categories.js: sidebar labels + NEW list ─────────────────────────────
  const catPath = join(VENDOR, "constants/Categories.js");
  let cat = await readFile(catPath, "utf8");
  let labelSwaps = 0;
  const labelToRename = new Map<string, Rename>();
  // Replace every quoted label whose normalized form matches a free rename,
  // but only inside the label arrays — heuristics: quoted strings on their own
  // lines. Applied file-wide is safe here: this constants file is labels only.
  cat = cat.replace(/'([^']+)'/g, (m, label) => {
    const r = byNorm.get(norm(label));
    if (!r || r.newTitle === label) return m;
    labelToRename.set(label, r);
    labelSwaps++;
    return `'${r.newTitle}'`;
  });
  await writeFile(catPath, cat, "utf8");
  console.log(`  Categories.js: ${labelSwaps} labels renamed`);

  // ── Components.js: REAL keys become the new slugs ────────────────────────
  // "No old names; the ref sheet is the only tie" (user, 2026-08-15): the map's
  // real keys are rewritten in place, and the OLD slugs become compat aliases
  // generated from the sheet — old URLs keep resolving, but every old-name
  // string in the file is a regenerable artifact of renames.json. Prior-pairs
  // recovery keeps re-runs idempotent after the old keys are gone (handles the
  // legacy new→old alias direction too, by inverting it).
  const compPath = join(VENDOR, "constants/Components.js");
  const rawComp = await readFile(compPath, "utf8");
  const newSlugSet = new Set(free.map((r) => r.newSlug));
  const compPairs = new Map<string, string>(); // oldKey -> newSlug
  for (const m of rawComp.matchAll(/componentMap\['([^']+)'\] = componentMap\['([^']+)'\];/g)) {
    const [, a, b] = m as unknown as [string, string, string];
    if (newSlugSet.has(b) && !newSlugSet.has(a)) compPairs.set(a, b);
    else if (newSlugSet.has(a) && !newSlugSet.has(b)) compPairs.set(b, a);
  }
  let comp = stripBlock(rawComp);
  const existingKeys = [...comp.matchAll(/'([a-z0-9-]+)':\s*\(\)\s*=>\s*import/g)].map((m) => m[1]!);
  let keyRewrites = 0;
  for (const key of existingKeys) {
    const r = byNorm.get(norm(key));
    if (r && r.newSlug !== key) {
      comp = comp.replace(`'${key}':`, `'${r.newSlug}':`);
      compPairs.set(key, r.newSlug);
      keyRewrites++;
    }
  }
  const aliasLines = [...compPairs.entries()]
    .filter(([, neu]) => comp.includes(`'${neu}':`))
    .map(([oldKey, neu]) => `componentMap['${oldKey}'] = componentMap['${neu}'];`);
  comp += `\n${START}\n${aliasLines.join("\n")}\n${END}\n`;
  await writeFile(compPath, comp, "utf8");
  console.log(`  Components.js: ${keyRewrites} keys renamed in place, ${aliasLines.length} compat aliases`);

  // ── Information.js: rename the REAL entries ──────────────────────────────
  // The first version aliased new keys onto the old entries by reference. Two
  // runtime bugs fell out (audit 2026-08-14): the aliased object keeps its old
  // `name:` field, which ComponentList/Favorites display, so every card showed
  // the OLD title; and Object.entries() enumerates both keys, so Browse All
  // listed every component twice. So: rewrite key + `name:` in place, and make
  // the OLD keys non-enumerable compat aliases (direct lookup for old routes
  // still works; enumeration sees each component once, under its new name).
  const infoPath = join(VENDOR, "constants/Information.js");
  let rawInfo = await readFile(infoPath, "utf8");
  // Re-run support: recover the old↔new pairs recorded by a previous run
  // before stripping its block (the old keys are gone from the table by then).
  const priorPairs = [...rawInfo.matchAll(/defineProperty\(componentMetadata, '([^']+)', \{ value: componentMetadata\['([^']+)'\]/g)]
    .map((m) => ({ oldKey: m[1]!, newKey: m[2]! }));
  let info = stripBlock(rawInfo);
  const metaKeys = [...info.matchAll(/'((?:Animations|TextAnimations|Components|Backgrounds)\/[A-Za-z0-9]+)':/g)].map((m) => m[1]!);
  const decode = (slug: string) => slug.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  const pairs = new Map(priorPairs.map((p) => [p.oldKey, p.newKey]));
  let rewrites = 0;
  for (const key of metaKeys) {
    const [catKey, name] = key.split("/") as [string, string];
    const r = byNorm.get(norm(name));
    if (!r) continue;
    const newName = decode(r.newSlug).replace(/\s+/g, "");
    const newKey = `${catKey}/${newName}`;
    if (newKey === key) continue;
    if (metaKeys.includes(newKey)) { console.log(`  !! key collision, skipped: ${key} -> ${newKey}`); continue; }
    info = info.replace(`'${key}':`, `'${newKey}':`);
    info = info.replace(`name: '${name}'`, `name: '${newName}'`);
    pairs.set(key, newKey);
    rewrites++;
  }
  const compat = [...pairs.entries()]
    .filter(([, newKey]) => info.includes(`'${newKey}':`))
    .map(([oldKey, newKey]) =>
      `Object.defineProperty(componentMetadata, '${oldKey}', { value: componentMetadata['${newKey}'], enumerable: false, configurable: true });`);
  info += `\n${START}\n${compat.join("\n")}\n${END}\n`;
  await writeFile(infoPath, info, "utf8");
  console.log(`  Information.js: ${rewrites} entries renamed in place, ${compat.length} hidden compat keys`);

  // ── Features.jsx: homepage marquee ───────────────────────────────────────
  // Hand-authored {name, cat} arrays disconnected from the constants — the
  // pill label AND its route both derive from `name`, so one swap fixes both
  // (new-slug routes resolve via the componentMap aliases).
  const featPath = join(VENDOR, "components/landingnew/Features/Features.jsx");
  let feat = await readFile(featPath, "utf8");
  let featSwaps = 0;
  feat = feat.replace(/name: '([^']+)'/g, (m, label) => {
    const r = byNorm.get(norm(label));
    if (!r || r.newTitle === label) return m;
    featSwaps++;
    return `name: '${r.newTitle}'`;
  });
  await writeFile(featPath, feat, "utf8");
  console.log(`  Features.jsx: ${featSwaps} marquee labels renamed`);

  // Coverage report — free renames that never matched anything on the site.
  const matched = new Set([...labelToRename.values()].map((r) => r.slug));
  for (const k of existingKeys) { const r = byNorm.get(norm(k)); if (r) matched.add(r.slug); }
  const unmatched = free.filter((r) => !matched.has(r.slug)).map((r) => r.slug);
  if (unmatched.length) console.log(`  !! unmatched free renames (${unmatched.length}): ${unmatched.join(", ")}`);
}

main();
